//
//  PGPPacketParsingTests.swift
//  SwiftPGPTests
//

import XCTest
@testable import SwiftPGP

final class PGPPacketParsingTests: XCTestCase {
    
    // Test data: Simple RSA Public Key (generated by GnuPG or similar)
    // This is a dummy packet for testing header parsing logic, not a real valid RSA key body
    func testPacketHeaderParsing() {
        // Old Format: Tag 6 (Public Key), Length 5 bytes
        // Tag byte: 10 0110 00 (0x98) -> 10 (Old) | 0110 (6) | 00 (1 byte length)
        // Length: 05
        // Body: 01 02 03 04 05
        let oldFormatData = Data([0x98, 0x05, 0x01, 0x02, 0x03, 0x04, 0x05])
        
        guard let (body, tag, headerLength, consumed) = PGPPacket.readPacketBody(from: oldFormatData) else {
            XCTFail("Failed to parse old format packet")
            return
        }
        
        XCTAssertEqual(tag, .publicKey)
        XCTAssertEqual(headerLength, 2) // 1 tag + 1 len
        XCTAssertEqual(consumed, 7)
        XCTAssertEqual(body, Data([0x01, 0x02, 0x03, 0x04, 0x05]))
    }
    
    func testNewFormatHeaderParsing() {
        // New Format: Tag 2 (Signature), Length 100 bytes
        // Tag byte: 11 000010 (0xC2) -> 1 (New) | 1 (New) | 000010 (2)
        // Length: 100 (0x64) -> One octet < 192
        let bodyData = Data(repeating: 0xAA, count: 100)
        var packetData = Data([0xC2, 0x64])
        packetData.append(bodyData)
        
        guard let (body, tag, headerLength, consumed) = PGPPacket.readPacketBody(from: packetData) else {
            XCTFail("Failed to parse new format packet")
            return
        }
        
        XCTAssertEqual(tag, .signature)
        XCTAssertEqual(headerLength, 2) // 1 tag + 1 len
        XCTAssertEqual(consumed, 102)
        XCTAssertEqual(body, bodyData)
    }
    
    func testPublicKeyPacketParsing() {
        // Construct a minimal Public Key Packet
        // Version 4 (1 byte)
        // Timestamp (4 bytes)
        // Algo RSA (1 byte)
        // Key Data (arbitrary for now)
        
        let timestamp: UInt32 = 1600000000
        var body = Data([0x04])
        var ts = timestamp.bigEndian
        body.append(Data(bytes: &ts, count: 4))
        body.append(PGPPublicKeyAlgorithm.rsa.rawValue)
        body.append(Data([0x01, 0x02, 0x03])) // Fake MPIs
        
        let header = PGPPacket.buildHeader(tag: .publicKey, bodyLength: body.count)
        let fullData = header + body
        
        guard let packets = try? PGPPacketFactory.packets(from: fullData),
              let keyPacket = packets.first as? PGPPublicKeyPacket else {
            XCTFail("Failed to parse Public Key Packet")
            return
        }
        
        XCTAssertEqual(keyPacket.version, 4)
        XCTAssertEqual(keyPacket.publicKeyAlgorithm, .rsa)
        XCTAssertEqual(keyPacket.createDate.timeIntervalSince1970, TimeInterval(timestamp))
    }
    
    func testReadKeysIntegration() {
        // Test reading keys through SwiftPGP.readKeys
        // We'll construct a key with one Public Key packet and one User ID packet
        
        // 1. Public Key Packet
        let timestamp: UInt32 = 1600000000
        var pkBody = Data([0x04])
        var ts = timestamp.bigEndian
        pkBody.append(Data(bytes: &ts, count: 4))
        pkBody.append(PGPPublicKeyAlgorithm.rsa.rawValue)
        pkBody.append(Data([0xFF])) // Dummy key data
        let pkHeader = PGPPacket.buildHeader(tag: .publicKey, bodyLength: pkBody.count)
        
        // 2. User ID Packet
        let userId = "Test User"
        let uidBody = userId.data(using: .utf8)!
        let uidHeader = PGPPacket.buildHeader(tag: .userID, bodyLength: uidBody.count)
        
        let fileData = pkHeader + pkBody + uidHeader + uidBody
        
        do {
            let keys = try SwiftPGP.readKeys(fromData: fileData)
            XCTAssertEqual(keys.count, 1)
            let key = keys.first
            XCTAssertNotNil(key?.publicKey)
            XCTAssertEqual(key?.publicKey?.users.first?.userID, "Test User")
            XCTAssertEqual(key?.publicKey?.primaryKeyPacket?.createDate.timeIntervalSince1970, TimeInterval(timestamp))
        } catch {
            XCTFail("Read keys failed: \(error)")
        }
    }
}

